// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_A3PmNGJd5lltLalypm9EEphISCW5jqw',
    appId: '1:477851402672:web:3865f2418ef82cfca49675',
    messagingSenderId: '477851402672',
    projectId: 'mimenu-98519',
    authDomain: 'mimenu-98519.firebaseapp.com',
    storageBucket: 'mimenu-98519.appspot.com',
    measurementId: 'G-73TMRXB945',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBngJQRb03inyvpkxRHQ7yCljfhdZHxGQY',
    appId: '1:477851402672:android:d55511e85c3c95d1a49675',
    messagingSenderId: '477851402672',
    projectId: 'mimenu-98519',
    storageBucket: 'mimenu-98519.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7LzPe0SF2bBhQmVzL-Yg4dY4-PPwif3g',
    appId: '1:477851402672:ios:8fa7bcb49e24ea23a49675',
    messagingSenderId: '477851402672',
    projectId: 'mimenu-98519',
    storageBucket: 'mimenu-98519.appspot.com',
    iosBundleId: 'com.example.homeRestaurant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7LzPe0SF2bBhQmVzL-Yg4dY4-PPwif3g',
    appId: '1:477851402672:ios:0ac58e2503d43c15a49675',
    messagingSenderId: '477851402672',
    projectId: 'mimenu-98519',
    storageBucket: 'mimenu-98519.appspot.com',
    iosBundleId: 'com.example.homeRestaurant.RunnerTests',
  );
}
